import { Link } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BadgeCheck, Compass, HandHeart, Sparkles, Play } from 'lucide-react'
import { properties, agents, testimonials } from '../data'
import PropertyCard from '../components/PropertyCard'
import AgentCard from '../components/AgentCard'
import SearchBar from '../components/SearchBar'
import SectionHeading from '../components/SectionHeading'
import TestimonialCard from '../components/TestimonialCard'

export default function Home({ favorites, toggleFavorite }) { return <>
  <section className="relative min-h-[680px] overflow-hidden bg-ink text-cream"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=90" alt="Modern home interior" className="absolute inset-0 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-r from-ink/90 via-ink/55 to-ink/10" /><div className="container-shell relative flex min-h-[680px] flex-col justify-center pb-20 pt-24"><div className="max-w-2xl fade-up"><p className="eyebrow mb-6">A better way home</p><h1 className="font-display text-6xl leading-[.85] sm:text-8xl">Find a place<br /><i className="font-normal text-bronze">you'll love</i><br />to call home.</h1><p className="mt-7 max-w-md text-sm leading-7 text-cream/70">Discover exceptional homes, apartments and investment properties in the locations that matter to you.</p></div><div className="mt-14 max-w-5xl fade-up [animation-delay:150ms]"><SearchBar /><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-cream/60"><span>10,000+ properties</span><span>•</span><span>2,500+ happy clients</span><span>•</span><span>Trusted local experts</span></div></div></div></section>
  <section className="container-shell py-24"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="The collection" title="Homes worth coming home to." text="Handpicked properties selected for exceptional living, from quiet retreats to vibrant city addresses." /><Link to="/properties" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-ink hover:text-bronze">Explore all properties <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{properties.map((property) => <PropertyCard key={property.id} property={property} favorite={favorites.includes(property.id)} onFavorite={toggleFavorite} />)}</div></section>
  <section className="bg-sand/60 py-24"><div className="container-shell"><div className="grid items-center gap-14 lg:grid-cols-[1.1fr_1fr]"><div className="relative"><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85" alt="Elegant Nestora living room" className="aspect-[1.1] w-full object-cover" /><div className="absolute -bottom-7 -right-4 bg-ink p-6 text-cream sm:-right-8"><p className="font-display text-5xl">15+</p><p className="mt-1 text-[10px] uppercase tracking-widest text-cream/60">Years of experience</p></div></div><div id="about"><SectionHeading eyebrow="The Nestora difference" title="A more thoughtful way to move." text="A home is more than its address. It is the backdrop to your life, the place that holds your everyday rituals and your biggest moments. We bring a considered, human approach to every search." /><Link to="/contact" className="mt-8 inline-flex items-center gap-2 border-b border-ink pb-2 text-xs font-bold uppercase tracking-widest transition hover:border-bronze hover:text-bronze">Meet our approach <ArrowRight size={15} /></Link></div></div><div className="mt-24 grid gap-8 border-t border-ink/15 pt-10 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck, 'Verified Properties', 'Every listing is carefully checked and clearly represented.'], [Compass, 'Local Expertise', 'Deep neighborhood insight beyond the brochure.'], [HandHeart, 'Personal Guidance', 'A dedicated expert, from first search to closing.'], [Sparkles, 'Seamless Experience', 'Thoughtful tools and calm communication throughout.']].map(([Icon, title, text]) => <div key={title}><Icon size={21} className="text-bronze" /><h3 className="mt-5 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-6 text-ink/55">{text}</p></div>)}</div></div></section>
  <section className="bg-ink py-20 text-cream"><div className="container-shell grid grid-cols-2 gap-y-12 sm:grid-cols-4">{[['10,000+', 'Properties Listed'], ['2,500+', 'Happy Clients'], ['150+', 'Expert Agents'], ['15+', 'Years of Experience']].map(([number, label]) => <div key={label} className="border-l border-cream/20 pl-5"><p className="font-display text-5xl">{number}</p><p className="mt-2 text-[10px] uppercase tracking-widest text-cream/50">{label}</p></div>)}</div></section>
  <section className="container-shell py-24"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Your people" title="Local experts. Personal advice." text="Meet the people who know the streets, the buildings and the feeling of finding the right place." /><Link to="/agents" className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest hover:text-bronze">Meet the team <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{agents.map((agent) => <AgentCard key={agent.name} agent={agent} />)}</div></section>
  <section className="bg-white py-24"><div className="container-shell"><div className="flex items-end justify-between"><SectionHeading eyebrow="Client notes" title="Good moves, told simply." /><div className="hidden items-center gap-2 text-xs text-ink/50 md:flex"><Play size={14} fill="currentColor" /> Real stories from the Nestora community</div></div><div className="mt-12 grid gap-10 md:grid-cols-3">{testimonials.map((item) => <TestimonialCard key={item.name} item={item} />)}</div></div></section>
  <section className="container-shell py-20"><div className="relative overflow-hidden bg-bronze px-7 py-16 text-center text-cream sm:px-16"><div className="absolute -right-12 -top-24 h-72 w-72 rounded-full border border-cream/20" /><div className="relative"><p className="eyebrow !text-cream/70">Your next chapter</p><h2 className="mx-auto mt-4 max-w-xl font-display text-5xl leading-none md:text-7xl">Ready to find your next home?</h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-cream/75">Tell us what you're looking for and our property experts will help you find the right place.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/properties" className="bg-ink px-6 py-3 text-xs font-bold uppercase tracking-widest transition hover:bg-white hover:text-ink">Explore Properties</Link><Link to="/contact" className="border border-cream/50 px-6 py-3 text-xs font-bold uppercase tracking-widest transition hover:bg-white hover:text-ink">Talk to an Expert</Link></div></div></div></section>
</> }
